name: Racket Test

on:
  push:
    branches:
      - "*"
    paths:
      - "**test.yml"
      - "**.rkt"
      - "**.scrbl"
  pull_request:
    branches:
      - "*"
    paths:
      - "**.rkt"
      - "**.scrbl"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-variant: ["CS"]
        racket-version: ["stable", "current"]
    steps:
      - uses: actions/checkout@master
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "13.0"
      - name: Cache installed packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/racket
            ~/.local/share/racket
            ${{ env.LLVM_PATH }}
          key: ${{ runner.os }}-primes
      - name: Setup Racket
        uses: Bogdanp/setup-racket@v1.7
        with:
          architecture: "x64" # (x64 or x86), ignored on Linux
          distribution: "minimal"
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - run: |
          export PATH=$PATH:${{ env.LLVM_PATH }}/bin
          raco pkg install --auto --skip-installed
          raco test .
